# Generated by Django 5.0.6 on 2024-05-26 03:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_customer_order_order_number_order_updated_at_and_more"),
        ("service", "0049_auto_20240526_0341"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("once", "One Time"),
                            ("weekly", "Bi-Weekly"),
                            ("semi_monthly", "Semi-Monthly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="order",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="order",
            name="description",
        ),
        migrations.AddField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="payment.customer",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="service.service",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="service_details",
            field=models.ManyToManyField(
                related_name="orders", to="service.servicedetail"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="order_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="payment.ordertype",
            ),
        ),
    ]
