state_choices = [
    ("AL", "Alabama"),
    ("AK", "Alaska"),
    ("AZ", "Arizona"),
    ("AR", "Arkansas"),
    ("CA", "California"),
    ("CO", "Colorado"),
    ("CT", "Connecticut"),
    ("DE", "Delaware"),
    ("FL", "Florida"),
    ("GA", "Georgia"),
    ("HI", "Hawaii"),
    ("ID", "Idaho"),
    ("IL", "Illinois"),
    ("IN", "Indiana"),
    ("IA", "Iowa"),
    ("KS", "Kansas"),
    ("KY", "Kentucky"),
    ("LA", "Louisiana"),
    ("ME", "Maine"),
    ("MD", "Maryland"),
    ("MA", "Massachusetts"),
    ("MI", "Michigan"),
    ("MN", "Minnesota"),
    ("MS", "Mississippi"),
    ("MO", "Missouri"),
    ("MT", "Montana"),
    ("NE", "Nebraska"),
    ("NV", "Nevada"),
    ("NH", "New Hampshire"),
    ("NJ", "New Jersey"),
    ("NM", "New Mexico"),
    ("NY", "New York"),
    ("NC", "North Carolina"),
    ("ND", "North Dakota"),
    ("OH", "Ohio"),
    ("OK", "Oklahoma"),
    ("OR", "Oregon"),
    ("PA", "Pennsylvania"),
    ("RI", "Rhode Island"),
    ("SC", "South Carolina"),
    ("SD", "South Dakota"),
    ("TN", "Tennessee"),
    ("TX", "Texas"),
    ("UT", "Utah"),
    ("VT", "Vermont"),
    ("VA", "Virginia"),
    ("WA", "Washington"),
    ("WV", "West Virginia"),
    ("WI", "Wisconsin"),
    ("WY", "Wyoming"),
    ("DC", "District of Columbia"),  # Washington D.C.
    ("AS", "American Samoa"),
    ("GU", "Guam"),
    ("MP", "Northern Mariana Islands"),
    ("PR", "Puerto Rico"),
    ("VI", "U.S. Virgin Islands"),
]

country_choices = [
    ("US", "United States"),
    ("CA", "Canada"),
    ("GB", "United Kingdom"),
    ("AU", "Australia"),
    ("DE", "Germany"),
    ("FR", "France"),
    ("IN", "India"),
    ("IT", "Italy"),
    ("JP", "Japan"),
    ("MX", "Mexico"),
    ("NL", "Netherlands"),
    ("NZ", "New Zealand"),
    ("SG", "Singapore"),
    ("ES", "Spain"),
    ("CH", "Switzerland"),
    ("BR", "Brazil"),
    ("AR", "Argentina"),
    ("CL", "Chile"),
    ("CO", "Colombia"),
    ("PE", "Peru"),
    ("VE", "Venezuela"),
    ("ZA", "South Africa"),
    ("NG", "Nigeria"),
    ("EG", "Egypt"),
    ("KE", "Kenya"),
    ("MA", "Morocco"),
    ("SA", "Saudi Arabia"),
    ("AE", "United Arab Emirates"),
    ("RU", "Russia"),
    ("CN", "China"),
    ("KR", "South Korea"),
    ("TW", "Taiwan"),
    ("TH", "Thailand"),
    ("PH", "Philippines"),
    ("ID", "Indonesia"),
    ("MY", "Malaysia"),
    ("VN", "Vietnam"),
    ("BD", "Bangladesh"),
    ("PK", "Pakistan"),
    ("LK", "Sri Lanka"),
    ("NP", "Nepal"),
    ("IR", "Iran"),
    ("IQ", "Iraq"),
    ("SY", "Syria"),
    ("IL", "Israel"),
    ("JO", "Jordan"),
    ("LB", "Lebanon"),
    ("QA", "Qatar"),
    ("KW", "Kuwait"),
    ("OM", "Oman"),
    ("BH", "Bahrain"),
    ("CY", "Cyprus"),
    ("FI", "Finland"),
    ("SE", "Sweden"),
    ("NO", "Norway"),
    ("DK", "Denmark"),
    ("PL", "Poland"),
    ("UA", "Ukraine"),
    ("HU", "Hungary"),
    ("CZ", "Czech Republic"),
    ("AT", "Austria"),
    ("BE", "Belgium"),
    ("PT", "Portugal"),
    ("IE", "Ireland"),
    ("GR", "Greece"),
    ("RO", "Romania"),
    ("HR", "Croatia"),
    ("RS", "Serbia"),
    ("BG", "Bulgaria"),
    ("SI", "Slovenia"),
    ("LT", "Lithuania"),
    ("LV", "Latvia"),
    ("EE", "Estonia"),
    ("BY", "Belarus"),
    ("MD", "Moldova"),
    ("AL", "Albania"),
    ("MK", "North Macedonia"),
    ("XK", "Kosovo"),
    ("BA", "Bosnia and Herzegovina"),
    ("ME", "Montenegro"),
    ("XK", "Kosovo"),
    ("IS", "Iceland"),
    ("FO", "Faroe Islands"),
    ("GL", "Greenland"),
    ("GI", "Gibraltar"),
    ("IM", "Isle of Man"),
    ("MQ", "Martinique"),
    ("RE", "Réunion"),
    ("YT", "Mayotte"),
    ("GF", "French Guiana"),
    ("PM", "Saint Pierre and Miquelon"),
    ("WF", "Wallis and Futuna"),
    ("PF", "French Polynesia"),
    ("NC", "New Caledonia"),
    ("TF", "French Southern and Antarctic Lands"),
    ("AI", "Anguilla"),
    ("BM", "Bermuda"),
    ("VG", "British Virgin Islands"),
    ("KY", "Cayman Islands"),
    ("FK", "Falkland Islands"),
    ("GI", "Gibraltar"),
    ("MS", "Montserrat"),
    ("PN", "Pitcairn Islands"),
    ("SH", "Saint Helena, Ascension and Tristan da Cunha"),
    ("GS", "South Georgia and the South Sandwich Islands"),
    ("TC", "Turks and Caicos Islands"),
    ("AX", "Åland Islands"),
    ("CC", "Cocos (Keeling) Islands"),
    ("CX", "Christmas Island"),
    ("HM", "Heard Island and McDonald Islands"),
    ("NF", "Norfolk Island"),
    ("BL", "Saint Barthélemy"),
    ("MF", "Saint Martin"),
    ("SX", "Sint Maarten"),
    ("BQ", "Caribbean Netherlands"),
    ("CW", "Curaçao"),
    ("GG", "Guernsey"),
    ("JE", "Jersey"),
    ("XK", "Kosovo"),
    ("AI", "Anguilla"),
    ("BM", "Bermuda"),
    ("VG", "British Virgin Islands"),
    ("KY", "Cayman Islands"),
    ("FK", "Falkland Islands"),
    ("GI", "Gibraltar"),
    ("MS", "Montserrat"),
    ("SH", "Saint Helena, Ascension and Tristan da Cunha"),
    ("AX", "Åland Islands"),
    ("CC", "Cocos (Keeling) Islands"),
    ("CX", "Christmas Island"),
    ("HM", "Heard Island and McDonald Islands"),
    ("SX", "Sint Maarten"),
    ("BQ", "Caribbean Netherlands"),
    ("CW", "Curaçao"),
    ("GG", "Guernsey"),
    ("JE", "Jersey"),
    ("MO", "Macao"),
    ("MS", "Montserrat"),
    ("NU", "Niue"),
    ("MP", "Northern Mariana Islands"),
    ("SH", "Saint Helena"),
    ("PM", "Saint Pierre and Miquelon"),
    ("SJ", "Svalbard and Jan Mayen"),
    ("UM", "United States Minor Outlying Islands"),
    ("WF", "Wallis and Futuna"),
    ("EH", "Western Sahara"),
]
