# Generated by Django 4.2.10 on 2024-05-19 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.location'),
        ),
    ]
