# Generated by Django 4.2.10 on 2024-05-23 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_remove_business_location_remove_profile_business_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='location',
            field=models.ManyToManyField(null=True, related_name='locations', to='service.location'),
        ),
    ]
