# Generated by Django 4.2.10 on 2024-05-21 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_service_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedetail',
            name='image',
            field=models.URLField(blank=True, default='https://via.placeholder.com/150', null=True),
        ),
    ]
