# Generated by Django 4.2.10 on 2024-05-22 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_servicedetail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.location'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_inputs', to='service.servicedetail'),
        ),
        migrations.AlterField(
            model_name='service',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_services', to='service.company'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='service.service'),
        ),
    ]
