# Generated by Django 4.2.10 on 2024-05-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_business_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='location',
            field=models.ManyToManyField(blank=True, null=True, related_name='locations', to='service.location'),
        ),
    ]
