# Generated by Django 4.2.10 on 2024-05-23 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_business_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_permissions',
        ),
    ]
