# Generated by Django 4.2.10 on 2024-05-22 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_company_location_alter_detail_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedetail',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='price',
            field=models.IntegerField(),
        ),
    ]
