# Generated by Django 4.2.10 on 2024-05-22 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_address_remove_schedule_vendor_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='Business',
        ),
        migrations.RenameField(
            model_name='servicedetail',
            old_name='provider',
            new_name='service',
        ),
    ]
