# Generated by Django 4.2.10 on 2024-05-22 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_rename_company_business_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='company',
            new_name='service',
        ),
    ]
