# Generated by Django 5.0.6 on 2024-05-26 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0008_auto_20240526_0054"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="appointment",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="user",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="service",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="vendor",
        ),
        migrations.DeleteModel(
            name="Appointment",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
        migrations.DeleteModel(
            name="Schedule",
        ),
    ]
