# Generated by Django 4.2.10 on 2024-05-22 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_rename_company_service_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='service.servicedetail'),
        ),
    ]
