# Generated by Django 5.0.6 on 2024-05-26 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "service",
            "0009_remove_payment_appointment_remove_notification_user_and_more",
        ),
    ]

    operations = []
