# Generated by Django 5.0.6 on 2024-05-26 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0014_servicetime_subscription_service_customizable_and_more"),
    ]

    operations = []
