# Generated by Django 5.0.6 on 2024-05-26 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0015_auto_20240526_0207"),
    ]

    operations = []
