# Generated by Django 5.0.6 on 2024-05-26 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0016_auto_20240526_0207"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="location",
            field=models.ManyToManyField(
                blank=True, related_name="locations", to="service.address"
            ),
        ),
    ]
