# Generated by Django 5.0.6 on 2024-05-26 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0019_auto_20240526_0213"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="service_radius",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
