# Generated by Django 5.0.6 on 2024-05-26 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0023_remove_service_locations"),
    ]

    operations = []
