# Generated by Django 5.0.6 on 2024-05-26 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0026_remove_service_price_serviceprice"),
    ]

    operations = []
