# Generated by Django 5.0.6 on 2024-05-26 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0028_auto_20240526_0229"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="is_subscribable",
        ),
        migrations.AddField(
            model_name="serviceprice",
            name="is_subscribable",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="service",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="service.category",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="subcategories",
            field=models.ManyToManyField(
                blank=True, related_name="services", to="service.subcategory"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="service.subscription",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="time",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="service.servicetime",
            ),
        ),
    ]
