# Generated by Django 5.0.6 on 2024-05-26 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0029_remove_service_is_subscribable_and_more"),
    ]

    operations = []
