# Generated by Django 5.0.6 on 2024-05-26 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0032_remove_servicedetail_duration_max_and_more"),
    ]

    operations = []
