# Generated by Django 5.0.6 on 2024-05-26 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0041_auto_20240526_0304"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="time",
            new_name="time_estimate",
        ),
        migrations.RenameField(
            model_name="serviceprice",
            old_name="price",
            new_name="amount",
        ),
        migrations.RenameField(
            model_name="serviceprice",
            old_name="tier",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="servicetime",
            name="length",
        ),
        migrations.AddField(
            model_name="business",
            name="type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="servicedetail",
            name="time",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="additional_time",
                to="service.servicetime",
            ),
        ),
        migrations.AddField(
            model_name="servicetime",
            name="estimate",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="servicetime",
            name="max",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servicetime",
            name="min",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servicetime",
            name="unit",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="serviceprice",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_price",
                to="service.service",
            ),
        ),
        migrations.AlterField(
            model_name="serviceprice",
            name="service_detail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="additional_cost",
                to="service.servicedetail",
            ),
        ),
    ]
