# Generated by Django 5.0.6 on 2024-05-26 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0042_rename_time_service_time_estimate_and_more"),
    ]

    operations = []
