# Generated by Django 5.0.6 on 2024-05-26 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0043_auto_20240526_0332"),
    ]

    operations = []
