# Generated by Django 5.0.6 on 2024-05-26 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0044_auto_20240526_0332"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="service",
        ),
        migrations.RemoveField(
            model_name="review",
            name="user",
        ),
        migrations.RemoveField(
            model_name="detail",
            name="price",
        ),
        migrations.AlterField(
            model_name="detail",
            name="service_detail",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="service.servicedetail"
            ),
        ),
        migrations.DeleteModel(
            name="CustomServiceOption",
        ),
        migrations.DeleteModel(
            name="Review",
        ),
    ]
