# Generated by Django 5.0.6 on 2024-05-26 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0045_remove_review_service_remove_review_user_and_more"),
    ]

    operations = []
