#Contractors
contractors = [
    {'username': 'naruto_uzumaki', 'email': 'naruto.uzumaki@example.com', 'role': 'contractor', 'phone': '513-555-0101'},
    {'username': 'sasuke_uchiha', 'email': 'sasuke.uchiha@example.com', 'role': 'contractor', 'phone': '513-555-0102'},
    {'username': 'sakura_haruno', 'email': 'sakura.haruno@example.com', 'role': 'contractor', 'phone': '513-555-0103'},
    {'username': 'kakashi_hatake', 'email': 'kakashi.hatake@example.com', 'role': 'contractor', 'phone': '513-555-0104'},
    {'username': 'hinata_hyuga', 'email': 'hinata.hyuga@example.com', 'role': 'contractor', 'phone': '513-555-0105'},
    {'username': 'shikamaru_nara', 'email': 'shikamaru.nara@example.com', 'role': 'contractor', 'phone': '513-555-0106'},
    {'username': 'neji_hyuga', 'email': 'neji.hyuga@example.com', 'role': 'contractor', 'phone': '513-555-0107'},
    {'username': 'rock_lee', 'email': 'rock.lee@example.com', 'role': 'contractor', 'phone': '513-555-0108'},
    {'username': 'tenten', 'email': 'tenten@example.com', 'role': 'contractor', 'phone': '513-555-0109'},
    {'username': 'ino_yamanaka', 'email': 'ino.yamanaka@example.com', 'role': 'contractor', 'phone': '513-555-0110'},
    {'username': 'choji_akimichi', 'email': 'choji.akimichi@example.com', 'role': 'contractor', 'phone': '513-555-0111'},
    {'username': 'gaara', 'email': 'gaara@example.com', 'role': 'contractor', 'phone': '513-555-0112'},
    {'username': 'kiba_inuzuka', 'email': 'kiba.inuzuka@example.com', 'role': 'contractor', 'phone': '513-555-0113'},
    {'username': 'shino_aburame', 'email': 'shino.aburame@example.com', 'role': 'contractor', 'phone': '513-555-0114'},
    {'username': 'temari', 'email': 'temari@example.com', 'role': 'contractor', 'phone': '513-555-0115'},
    {'username': 'kankuro', 'email': 'kankuro@example.com', 'role': 'contractor', 'phone': '513-555-0116'},
    {'username': 'might_guy', 'email': 'might.guy@example.com', 'role': 'contractor', 'phone': '513-555-0117'},
    {'username': 'tsunade', 'email': 'tsunade@example.com', 'role': 'contractor', 'phone': '513-555-0118'},
    {'username': 'jiraiya', 'email': 'jiraiya@example.com', 'role': 'contractor', 'phone': '513-555-0119'},
    {'username': 'orochimaru', 'email': 'orochimaru@example.com', 'role': 'contractor', 'phone': '513-555-0120'},
    {'username': 'hashirama_senju', 'email': 'hashirama.senju@example.com', 'role': 'contractor', 'phone': '513-555-0121'},
    {'username': 'tobirama_senju', 'email': 'tobirama.senju@example.com', 'role': 'contractor', 'phone': '513-555-0122'},
    {'username': 'hiruzen_sarutobi', 'email': 'hiruzen.sarutobi@example.com', 'role': 'contractor', 'phone': '513-555-0123'},
    {'username': 'minato_namikaze', 'email': 'minato.namikaze@example.com', 'role': 'contractor', 'phone': '513-555-0124'},
    {'username': 'kushina_uzumaki', 'email': 'kushina.uzumaki@example.com', 'role': 'contractor', 'phone': '513-555-0125'},
    {'username': 'itachi_uchiha', 'email': 'itachi.uchiha@example.com', 'role': 'contractor', 'phone': '513-555-0126'},
    {'username': 'madara_uchiha', 'email': 'madara.uchiha@example.com', 'role': 'contractor', 'phone': '513-555-0127'},
    {'username': 'obito_uchiha', 'email': 'obito.uchiha@example.com', 'role': 'contractor', 'phone': '513-555-0128'},
    {'username': 'kabuto_yakushi', 'email': 'kabuto.yakushi@example.com', 'role': 'contractor', 'phone': '513-555-0129'},
    {'username': 'hiruko', 'email': 'hiruko@example.com', 'role': 'contractor', 'phone': '513-555-0130'},
    {'username': 'kaguya_otsutsuki', 'email': 'kaguya.otsutsuki@example.com', 'role': 'contractor', 'phone': '513-555-0131'},
    {'username': 'hamura_otsutsuki', 'email': 'hamura.otsutsuki@example.com', 'role': 'contractor', 'phone': '513-555-0132'},
    {'username': 'hagoromo_otsutsuki', 'email': 'hagoromo.otsutsuki@example.com', 'role': 'contractor', 'phone': '513-555-0133'},
    {'username': 'kagami_uchiha', 'email': 'kagami.uchiha@example.com', 'role': 'contractor', 'phone': '513-555-0134'},
    {'username': 'dan_kato', 'email': 'dan.kato@example.com', 'role': 'contractor', 'phone': '513-555-0135'},
    {'username': 'torifu_akimichi', 'email': 'torifu.akimichi@example.com', 'role': 'contractor', 'phone': '513-555-0136'},
    {'username': 'jinpachi_munashi', 'email': 'jinpachi.munashi@example.com', 'role': 'contractor', 'phone': '513-555-0137'},
    {'username': 'menma_namikaze', 'email': 'menma.namikaze@example.com', 'role': 'contractor', 'phone': '513-555-0139'},
    {'username': 'fuguki_suikazan', 'email': 'fuguki.suikazan@example.com', 'role': 'contractor', 'phone': '513-555-0140'},
    {'username': 'zabuza_momochi', 'email': 'zabuza.momochi@example.com', 'role': 'contractor', 'phone': '513-555-0142'},
    {'username': 'kisame_hoshigaki', 'email': 'kisame.hoshigaki@example.com', 'role': 'contractor', 'phone': '513-555-0143'},
    {'username': 'konan', 'email': 'konan@example.com', 'role': 'contractor', 'phone': '513-555-0144'},
    {'username': 'yahiko', 'email': 'yahiko@example.com', 'role': 'contractor', 'phone': '513-555-0145'},
    {'username': 'nagato', 'email': 'nagato@example.com', 'role': 'contractor', 'phone': '513-555-0146'},
    {'username': 'han', 'email': 'han@example.com', 'role': 'contractor', 'phone': '513-555-0147'},
    {'username': 'sai', 'email': 'sai@example.com', 'role': 'contractor', 'phone': '513-555-0148'},
    {'username': 'utakata', 'email': 'utakata@example.com', 'role': 'contractor', 'phone': '513-555-0150'}
]

#Users
general = [
    {'username': 'ichigo_kurosaki', 'email': 'ichigo.kurosaki@example.com', 'role': 'general', 'phone': '513-555-0151'},
    {'username': 'rukia_kuchiki', 'email': 'rukia.kuchiki@example.com', 'role': 'general', 'phone': '513-555-0152'},
    {'username': 'renji_abarai', 'email': 'renji.abarai@example.com', 'role': 'general', 'phone': '513-555-0153'},
    {'username': 'byakuya_kuchiki', 'email': 'byakuya.kuchiki@example.com', 'role': 'general', 'phone': '513-555-0154'},
    {'username': 'toshiro_hitsugaya', 'email': 'toshiro.hitsugaya@example.com', 'role': 'general', 'phone': '513-555-0155'},
    {'username': 'ichimaru_gin', 'email': 'ichimaru.gin@example.com', 'role': 'general', 'phone': '513-555-0157'},
    {'username': 'sosuke_aizen', 'email': 'sosuke.aizen@example.com', 'role': 'general', 'phone': '513-555-0158'},
    {'username': 'ulquiorra_cifer', 'email': 'ulquiorra.cifer@example.com', 'role': 'general', 'phone': '513-555-0159'},
    {'username': 'orihime_inoue', 'email': 'orihime.inoue@example.com', 'role': 'general', 'phone': '513-555-0160'},
    {'username': 'uryu_ishida', 'email': 'uryu.ishida@example.com', 'role': 'general', 'phone': '513-555-0161'},
    {'username': 'yoruichi_shihoin', 'email': 'yoruichi.shihoin@example.com', 'role': 'general', 'phone': '513-555-0162'},
    {'username': 'kaname_tosen', 'email': 'kaname.tosen@example.com', 'role': 'general', 'phone': '513-555-0163'},
    {'username': 'grimmjow_jaegerjaquez', 'email': 'grimmjow.jaegerjaquez@example.com', 'role': 'general', 'phone': '513-555-0164'},
    {'username': 'sajin_komamura', 'email': 'sajin.komamura@example.com', 'role': 'general', 'phone': '513-555-0165'},
    {'username': 'nnoitra_gilga', 'email': 'nnoitra.gilga@example.com', 'role': 'general', 'phone': '513-555-0166'},
    {'username': 'tier_harribel', 'email': 'tier.harribel@example.com', 'role': 'general', 'phone': '513-555-0167'},
    {'username': 'baraggan_louisendbairn', 'email': 'baraggan.louisendbairn@example.com', 'role': 'general', 'phone': '513-555-0168'},
    {'username': 'coyote_starrk', 'email': 'coyote.starrk@example.com', 'role': 'general', 'phone': '513-555-0169'},
    {'username': 'mashiro_kuna', 'email': 'mashiro.kuna@example.com', 'role': 'general', 'phone': '513-555-0170'},
    {'username': 'kensei_muguruma', 'email': 'kensei.muguruma@example.com', 'role': 'general', 'phone': '513-555-0171'},
    {'username': 'shinji_hirako', 'email': 'shinji.hirako@example.com', 'role': 'general', 'phone': '513-555-0172'},
    {'username': 'love_aoi', 'email': 'love.aoi@example.com', 'role': 'general', 'phone': '513-555-0173'},
    {'username': 'rose_ose', 'email': 'rose.ose@example.com', 'role': 'general', 'phone': '513-555-0174'},
    {'username': 'lisa_yadomaru', 'email': 'lisa.yadomaru@example.com', 'role': 'general', 'phone': '513-555-0175'},
    {'username': 'kisuke_urahara', 'email': 'kisuke.urahara@example.com', 'role': 'general', 'phone': '513-555-0176'},
    {'username': 'yoruichi_shihoin', 'email': 'yoruichi.shihoin@example.com', 'role': 'general', 'phone': '513-555-0177'},
    {'username': 'jushiro_ukitake', 'email': 'jushiro.ukitake@example.com', 'role': 'general', 'phone': '513-555-0178'},
    {'username': 'shunsui_kyotake', 'email': 'shunsui.kyotake@example.com', 'role': 'general', 'phone': '513-555-0179'},
    {'username': 'nanao_ise', 'email': 'nanao.ise@example.com', 'role': 'general', 'phone': '513-555-0180'},
    {'username': 'genryusai_shigekuni_yamamoto', 'email': 'genryusai.shigekuni.yamamoto@example.com', 'role': 'general', 'phone': '513-555-0181'},
    {'username': 'sui_feng', 'email': 'sui.feng@example.com', 'role': 'general', 'phone': '513-555-0182'},
    {'username': 'marechiyo_o_maeda', 'email': 'marechiyo.o.maeda@example.com', 'role': 'general', 'phone': '513-555-0183'},
    {'username': 'isane_kotetsu', 'email': 'isane.kotetsu@example.com', 'role': 'general', 'phone': '513-555-0184'},
    {'username': 'yachiru_kusajishi', 'email': 'yachiru.kusajishi@example.com', 'role': 'general', 'phone': '513-555-0185'},
    {'username': 'ikaku_madarama', 'email': 'ikaku.madarama@example.com', 'role': 'general', 'phone': '513-555-0186'},
    {'username': 'riruka_dokugamine', 'email': 'riruka.dokugamine@example.com', 'role': 'general', 'phone': '513-555-0187'},
    {'username': 'yukio_hans_von_lee', 'email': 'yukio.hans.von.lee@example.com', 'role': 'general', 'phone': '513-555-0188'},
    {'username': 'jackie_tristan', 'email': 'jackie.tristan@example.com', 'role': 'general', 'phone': '513-555-0189'},
    {'username': 'ginjo_kugo', 'email': 'ginjo.kugo@example.com', 'role': 'general', 'phone': '513-555-0190'},
    {'username': 'giriko_kutsuzawa', 'email': 'giriko.kutsuzawa@example.com', 'role': 'general', 'phone': '513-555-0191'},
    {'username': 'gosuke_kano', 'email': 'gosuke.kano@example.com', 'role': 'general', 'phone': '513-555-0192'},
    {'username': 'shukuro_tsukishima', 'email': 'shukuro.tsukishima@example.com', 'role': 'general', 'phone': '513-555-0193'},
    {'username': 'x_cution', 'email': 'x.cution@example.com', 'role': 'general', 'phone': '513-555-0194'}
]

#Admins
admin_users = [
    {'username': 'chrisbrownofficial', 'email': 'chrisbrown@example.com', 'role': 'admin', 'phone': '513-555-0101'},
    {'username': 'sza937', 'email': 'sza@example.com', 'role': 'admin', 'phone': '614-555-0202'},
    {'username': 'beyoncequeen', 'email': 'beyonce@example.com', 'role': 'admin', 'phone': '330-555-0303'},
    {'username': 'drakethedrake', 'email': 'drake@example.com', 'role': 'admin', 'phone': '419-555-0404'},
    {'username': 'ladygagaofficial', 'email': 'ladygaga@example.com', 'role': 'admin', 'phone': '216-555-0505'},
    {'username': 'kendricklamar88', 'email': 'kendricklamar@example.com', 'role': 'admin', 'phone': '440-555-0606'},
    {'username': 'katyperryofficial', 'email': 'katyperry@example.com', 'role': 'admin', 'phone': '937-555-0707'},
    {'username': 'arianagrandeofficial', 'email': 'arianagrande@example.com', 'role': 'admin', 'phone': '330-555-0808'},
    {'username': 'theweekndxo', 'email': 'theweeknd@example.com', 'role': 'admin', 'phone': '513-555-0909'},
    {'username': 'edsheeranofficial', 'email': 'edsheeran@example.com', 'role': 'admin', 'phone': '937-555-1010'}
]
admins = [
    {'username': 'goku_saiyan', 'email': 'goku@example.com', 'role': 'admin', 'phone': '513-555-0101'},
    {'username': 'vegeta_prince', 'email': 'vegeta@example.com', 'role': 'admin', 'phone': '614-555-0202'},
    {'username': 'gohan_scholar', 'email': 'gohan@example.com', 'role': 'admin', 'phone': '330-555-0303'},
    {'username': 'piccolo_warrior', 'email': 'piccolo@example.com', 'role': 'admin', 'phone': '419-555-0404'},
    {'username': 'bulma_inventor', 'email': 'bulma@example.com', 'role': 'admin', 'phone': '216-555-0505'},
    {'username': 'krillin_monk', 'email': 'krillin@example.com', 'role': 'admin', 'phone': '440-555-0606'},
    {'username': 'trunks_time_traveler', 'email': 'trunks@example.com', 'role': 'admin', 'phone': '937-555-0707'},
    {'username': 'cell_perfect', 'email': 'cell@example.com', 'role': 'admin', 'phone': '330-555-0808'},
    {'username': 'frieza_emperor', 'email': 'frieza@example.com', 'role': 'admin', 'phone': '513-555-0909'},
    {'username': 'bulma_mother', 'email': 'bulma@example.com', 'role': 'admin', 'phone': '937-555-1010'}
]
