# Generated by Django 4.2.10 on 2024-05-23 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Servify User', 'verbose_name_plural': 'Servify Users'},
        ),
    ]
