# Generated by Django 5.0.6 on 2024-05-26 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_initial"),
    ]

    operations = []
