# Generated by Django 5.0.6 on 2024-05-26 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_auto_20240526_0056"),
    ]

    operations = []
