# Generated by Django 5.0.6 on 2024-05-26 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_notification"),
    ]

    operations = []
