# Generated by Django 5.0.6 on 2024-05-26 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0014_auto_20240526_0207"),
    ]

    operations = []
