# Generated by Django 5.0.6 on 2024-05-26 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0022_auto_20240526_0229"),
    ]

    operations = []
