# Generated by Django 5.0.6 on 2024-05-26 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0027_auto_20240526_0300"),
    ]

    operations = []
