# Generated by Django 5.0.6 on 2024-05-26 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0031_auto_20240526_0304"),
    ]

    operations = []
