# Generated by Django 5.0.6 on 2024-05-26 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0045_remove_review_service_remove_review_user_and_more"),
        ("user", "0034_auto_20240526_0332"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="location",
            field=models.ManyToManyField(blank=True, to="service.address"),
        ),
    ]
