# Generated by Django 5.0.6 on 2024-05-26 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0037_auto_20240526_0339"),
    ]

    operations = []
